language: java
install: true

jdk:
- oraclejdk8

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- ./gradlew assemble test jacocoTestReport



after_script:
- cp build/reports/jacoco/test/jacocoTestReport.xml build/jacoco.xml
- ./cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT
